### ISSUE TITLE
Plugin can accidentally toggle an artboard's visibility

### ISSUE THREAD

**Issue by bomberstudios** [ozgurgunes/Sketch-Layer-Comps#1]
We're getting some reports of users with documents where their artboards' visibility has been set to `false` and the only way to fix them is via a script, since there is not way in the UI to "unhide" an artboard (they can't be hidden, in the first place).

There is a possibility that your Plugin could be doing this, since (AFAICT) it doesn't check if a layer is an artboard or not before toggling its visibility.

Could you please take a look and see if you can add a check for that?

Thanks in advance!

**Comment by ozgurgunes** [comment]
Hello and thanks for your concern. 

I tested the plugin again, checked the codes, still can't reproduce the problem you wrote. Plugin processes the Layer Groups only if they're instance of `MSLayerGroup` class. Any others like instances of `MSShapeGroup` or `MSArtboardGroup` are being excluded in the show/hide process.

It is highly possible that problem you reported is caused by some other plugin or script.
